name: dsp-analysis
channels:
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - black=22.6.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - click=8.0.4
  - colorama=0.4.5
  - cycler=0.11.0
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - imageio=2.19.3
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.4
  - pathspec=0.9.0
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - py=1.11.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pytest=7.1.2
  - python=3.10.6
  - python-dateutil=2.8.2
  - pytz=2022.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - scipy=1.9.1
  - seaborn=0.11.2
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - charset-normalizer==2.1.1
    - ci-info==0.3.0
    - etelemetry==0.3.0
    - filelock==3.8.0
    - idna==3.4
    - isodate==0.6.1
    - looseversion==1.0.1
    - lxml==4.9.1
    - networkx==2.8.7
    - prov==2.0.0
    - pydot==1.4.2
    - rdflib==6.2.0
    - requests==2.28.1
    - simplejson==3.17.6
    - traits==6.3.2
    - urllib3==1.26.12
    - vc=14.2
    - libclang=12.0.0
    - vs2015_runtime=14.27.29016
    - wincertstore=0.2
    - icc_rt=2022.1.0
    - xlwings=0.27.15
    - pywin32=302
